version: '2'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  main:
    build: ./src
    command: ./run.sh
    ports:
      - '12345:12345'
    depends_on:
      - db
volumes:
  db:
    driver: local